export type SceneType = 'title' | 'problem' | 'solution' | 'example' | 'closing' | 'content';

/* ── Drawing primitives — generated by AI, animated by Remotion ── */
export type DrawPrimitive =
  | { type: 'line';   x1: number; y1: number; x2: number; y2: number; color?: string; w?: number }
  | { type: 'circle'; cx: number; cy: number; r: number; color?: string; fill?: boolean; w?: number }
  | { type: 'arc';    cx: number; cy: number; r: number; start: number; end: number; color?: string; w?: number }
  | { type: 'rect';   x: number; y: number; w: number; h: number; color?: string; fill?: boolean; sw?: number }
  | { type: 'poly';   points: [number, number][]; color?: string; fill?: boolean; w?: number }
  | { type: 'path';   d: string; color?: string; w?: number; fill?: boolean }
  | { type: 'text';   x: number; y: number; text: string; color?: string; size?: number; bold?: boolean }
  | { type: 'dot';    cx: number; cy: number; r?: number; color?: string }
  | { type: 'arrow';  x1: number; y1: number; x2: number; y2: number; color?: string; w?: number };

export interface QuizQuestion {
  type: 'single' | 'multiple' | 'text';
  question: string;
  options?: string[];
  correctAnswer: number | number[] | string;
  explanation?: string;
}

export interface WhiteboardScene {
  id: number;
  type: SceneType;
  title: string;
  subtitle: string;
  narration: string;
  bullets: string[];
  duration: number; // frames
  audioUrl: string | null;
  topic?: string;
  quiz?: QuizQuestion[];
  drawing?: DrawPrimitive[]; // AI-generated SVG primitives
}

export interface VideoConfig {
  topic: string;
  accentColor: string;
  boardStyle: 'classic' | 'dark' | 'chalk' | 'colorful';
  scenes: WhiteboardScene[];
}

export const BOARD_STYLES = {
  classic:  { bg: '#faf8f5', ink: '#2d2d2d', name: 'Clásica' },
  dark:     { bg: '#1a1a2e', ink: '#e0e0e0', name: 'Oscura' },
  chalk:    { bg: '#2d5016', ink: '#f0f0e8', name: 'Tiza' },
  colorful: { bg: '#fff5eb', ink: '#2d2d2d', name: 'Colorida' },
};
